### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by bsongis-frsky** [robthomson/rf2status#1]
Instead of:

```lua
if system.getSource("GPS Speed") ~= nil then
    temp_esc = system.getSource("GPS Speed"):value()
```

You could do:

```lua
local source = system.getSource("GPS Speed")
if source ~= nil then
    temp_esc = source:value()
```

Because `system:getSource(...)` costs CPU!

**Comment by bsongis-frsky** [comment]
I don't like too much this portion of code:

```lua
mah = system.getSource("Consumption"):stringValue()
if mah ~= nil then
    mah = sensorMakeNumber(mah)
else
    mah = 0
 end   
```

1) `stringValue()` creates a string, using the configurable decimals, unit, etc. you cannot rely on it, you don't know if you count carots or potatoes

2) `stringValue()` uses CPU. Show we speak about `sensorMakeNumber(...)`? which does exactly the opposite job! ;)

So I propose you just use `sensor:value()` when you want to do maths!

**Comment by robthomson** [comment]
Might be worth trying that.  Will mess with it over the weekend.

What odd is just that they result on different outcomes.

**Comment by robthomson** [comment]
All done and more :-)
