### ISSUE TITLE
Calculate Fuel Locally

### ISSUE THREAD

**Issue by jimmy6616** [robthomson/rf2status#4]
When you select local calculation, as an example attached. Main pack voltage is 22.58v and the calculation shows 56%

This should be reading approx 23%
![Calc_rfstatus](https://github.com/user-attachments/assets/fddbede6-3780-48ab-8947-4f946a75f0b2)

**Comment by robthomson** [comment]
Is your cell count correct?

**Comment by jimmy6616** [comment]
Yes , as discussed I’ve managed to adjust the sensor in Telemetry to display the correct voltage from the HW Esc. Would be better I believe to be able to adjust in RF or the LUA ?

**Comment by robthomson** [comment]
Lua is not right place to do this sort of adjustment ( in the end the lua is simply displaying values from the sensors)

But 100% agreed it shoulr be possible to adjust these values at source - on the fbl.

**Comment by jimmy6616** [comment]
Thanks Rob.

**Comment by jimmy6616** [comment]
Does your voltage reading get taken from the FBL or the sensor in Ethos ? I suspect the FBL as it’s still showing the original’ reading and not the adjusted voltage.

**Comment by robthomson** [comment]
The fbl is delivering the sensor to the radio.  So source is ultimately the fbl

**Comment by jimmy6616** [comment]
The readings between actual and displayed at 0.21v, which is enough to make the calculations a bit skewed

**Comment by robthomson** [comment]
For now you can adjust the value using the sensor in ethos.

This will help the issue.

Longer term it should be done on the fbl

**Comment by jimmy6616** [comment]
I’ve raised an issue on GitHub firmware 
Jim




On Sunday, September 22, 2024, 8:37 PM, Rob Thomson ***@***.***> wrote:




For now you can adjust the value using the sensor in ethos.

This will help the issue.

Longer term it should be done on the fbl

**Comment by robthomson** [comment]
Issue in the end is the source voltage.
